cbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('admin/', admin.site.urls),
                  path('', include('lesson_3.urls', namespace='lesson_3')),
                  path('auth-urls/', include('client_app.urls', namespace='client_app')),
                  path('vue-example/', include('vue_example.urls', namespace='vue')),
                  re_path(r'^api-auth/', include('rest_framework.urls'))
              ] + static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_app/urls.py
from django.urls import path, include, re_path
from . import views, auth_views

app_name = 'client_app'

urlpatterns = [
    path('cabinet', views.cabinet, name='cabinet'),
    path('all-articles', views.all_articles, name='all-articles'),
    path('change_color', views.change_color, name='change_color'),
    path('set-to-wish-list', views.set_to_session, name='set-to-wish-list'),
    path('write_post', views.write_post, name='write_post'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('wish-list/<int:pk>/', views.wish_list, name='wish-list'),
    path('article-item/<int:pk>',
         views.article_item,
         name='article-item'),
    path('add-commen/<int:article_id>', views.add_comment, name='add_comment'),
    path('filter_by_status/<str:status>',
         views.filter_by_status,
         name='filter_by_status'),
    path('delete_article/<int:pk>', views.delete_article, name='delete_article'),
    path('show_article/<int:pk>', views.show_article, name='show_article'),
    path('show-article-client/<int:pk>', views.show_article_client, name='show-article-client'),
]

auth_urls = [
    path('', auth_views.login_, name='login'),
    path('register', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

lesson_3/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'lesson_3'

urlpatterns = [
    path('', views.index, name='home'),
    path('all-authors', views.all_authors, name='authors'),
    path('book-info/<int:pk>', views.book_info, name='book-info'),
    path('all_book_for_authors/<int:id_author>',
         views.all_book_for_authors,
         name='all_book_for_authors'),
    path('calc', views.calc, name='calc'),
]

cbs/templates/pages/authors.html
{% extends 'index.html' %}

{% block content %}
    <h1>Все авторы ({{ authors|length }})</h1>

    {% for author in authors %}
        <p>Автор: <b>{{ author }}</b></p>
        <p>Кол-во книг : {{ author.books|length }}</p>
    {% endfor %}
{% endblock %}

cbs/templates/pages/book_info.html
{% extends 'index.html' %}

{% block content %}
<h1>{{ object.title }}</h1>
{% if object.preview %}
<img style="max-width: 100%" src="{{ object.preview.url }}"
     alt="{{ object.title }}" title="{{ object.text }}">
{% endif %}
<div class="text-justify">
    {{ object.text }}
</div>
<h3>
    <span>Автор - {{ object.author.get_full_name }} </span>
    <a href="{% url 'lesson_3:all_book_for_authors' id_author=object.author.id %}" class="btn btn-success">
        Все книги автора</a>
</h3>
<h4>Комментарии ({{ object.comments.all|length }}) </h4>

{% for comment in object.comments.all %}
<div>
    {% if not comment.user %}
    <p><a href="#">#anonymys</a></p>
    {% else %}
    <p><a href="#">#{{ comment.user }}</a></p>
    {% endif %}
    <p>{{ comment.msg }}</p>
    <p>{{ comment.date }}</p>
    <hr>
</div>

{% endfor %}

{% if request.user.is_authenticated %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <label for="">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for er in field.errors %}
                <p>{{ er }}</p>
            {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button class="btn btn-info">Отправить</button>
</form>

{% else %}
<p class="alert alert-primary">
    <a href="{% url 'client_app:login' %}">Войдите в систему , чтобы комментировать</a>
</p>
{% endif %}

{% endblock %}

cbs/templates/pages/calc.html
{% extends 'index.html' %}


{% block content %}
    <h1>Calculator</h1>

    <!-- simple html -->
    <form action="{% url 'lesson_3:calc' %}" method="POST">
        {% csrf_token %}
        <input type="number" name="first_number">
        <select name="operation" id="">
            {% for operation in operations %}
                <option value="{{ operation }}">{{ operation }}</option>
            {% endfor %}
        </select>

        <input type="number" name="second_number">

        <button class="btn btn-primary">Calculate</button>
        {% if result %}
            <p class="alert alert-info">{{ result }}</p>
        {% endif %}

        <div>
            <label for="check_me">Check me!</label>
            <input type="checkbox" name="check">
        </div>
        {#        <input type="submit">#}
        {#        {{operations}}#}
    </form>
{% endblock %}








{#        <input type="text">#}
{#        <input type="search" name="s">#}
{#        <input type="range">#}
{#        <input type="checkbox">#}
{##}
{#        <div>#}
{#            <input type="radio" name="a" value="car">#}
{#            <input type="radio" name="a" value="metro">#}
{#            <input type="radio" name="a" value="air">#}
{#            <input type="radio" name="a" value="">#}
{#            <input type="radio" name="a" value="">#}
{#            <input type="radio" name="a" value="">#}
{#        </div>#}
{##}
{#        <div>#}
{#            <select name="select" id="" multiple>#}
{#                <option value="-1">---</option>#}
{#                <option value="1">1</option>#}
{#                <option value="2">2</option>#}
{#                <option value="3">3</option>#}
{#                <option value="4">4</option>#}
{#            </select>#}
{#        </div>#}
{##}
{#        <textarea name="" id=""

cbs/templates/pages/home.html
{% extends 'index.html' %}
{% block content %}
<div class="row">
    {% for book in all_books %}
    <div class="card col-md-3" style="margin: 15px 10px">
        {% if book.preview %}
        <img class="card-img-top" src="{{ book.preview.url }}" alt="Card image cap">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.author.get_full_name }}</p>
            <a href="{% url 'lesson_3:book-info' pk=book.id %}" class="btn btn-info"> читать полностью</a>
            <form action="{% url 'client_app:set-to-wish-list' %}">
                <input type="hidden" name="article_id" value={{book.id}}>
                <button class="btn btn-warning">Отложить на чтение</button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}