cbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('admin/', admin.site.urls),
                  path('', include('lesson_3.urls', namespace='lesson_3')),
                  path('auth-urls/', include('client_app.urls', namespace='client_app')),
                  path('vue-example/', include('vue_example.urls', namespace='vue')),
                  re_path(r'^api-auth/', include('rest_framework.urls'))
              ] + static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_app/urls.py
from django.urls import path, include, re_path
from . import views, auth_views

app_name = 'client_app'

urlpatterns = [
    path('cabinet', views.cabinet, name='cabinet'),
    path('all-articles', views.all_articles, name='all-articles'),
    path('change_color', views.change_color, name='change_color'),
    path('set-to-wish-list', views.set_to_session, name='set-to-wish-list'),
    path('write_post', views.write_post, name='write_post'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('wish-list/<int:pk>/', views.wish_list, name='wish-list'),
    path('article-item/<int:pk>',
         views.article_item,
         name='article-item'),
    path('add-commen/<int:article_id>', views.add_comment, name='add_comment'),
    path('filter_by_status/<str:status>',
         views.filter_by_status,
         name='filter_by_status'),
    path('delete_article/<int:pk>', views.delete_article, name='delete_article'),
    path('show_article/<int:pk>', views.show_article, name='show_article'),
    path('show-article-client/<int:pk>', views.show_article_client, name='show-article-client'),
]

auth_urls = [
    path('', auth_views.login_, name='login'),
    path('register', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

lesson_3/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'lesson_3'

urlpatterns = [
    path('', views.index, name='home'),
    path('all-authors', views.all_authors, name='authors'),
    path('book-info/<int:pk>', views.book_info, name='book-info'),
    path('all_book_for_authors/<int:id_author>',
         views.all_book_for_authors,
         name='all_book_for_authors'),
    path('calc', views.calc, name='calc'),
]

client_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.translation import ugettext_lazy as _


class Author(models.Model):
    TYPE_USER_VIEW = (
        ('fio', 'ФИО'),
        ('pseudo_name', 'Псевдоним'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(max_length=5000,
                           verbose_name=_('Bio'),
                           blank=True, null=True)
    type_view = models.CharField(max_length=255,
                                 verbose_name=_('Тип представления'),
                                 choices=TYPE_USER_VIEW,
                                 blank=True, null=True)
    pseudoname = models.CharField(max_length=255,
                                  verbose_name=_('Псевдоним'),
                                  blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class Comment(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    msg = models.TextField(max_length=1000, verbose_name='Текст комментария')


class Article(models.Model):
    PUSBLISH_STATUS = (
        ('publish', 'Да'),
        ('unpublish', 'Нет'),
    )
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=255,
                             verbose_name='Title', blank=True,
                             null=True, default='')
    content = RichTextUploadingField()
    create_at = models.DateTimeField(auto_created=True, auto_now_add=True)
    status = models.CharField(max_length=55, verbose_name='Publish?', choices=PUSBLISH_STATUS)
    comments = models.ManyToManyField(Comment)

    def __str__(self):
        return '{} {} '.format(self.title, self.create_at)

    def __repr__(self):
        return 'this is object in sqlite data base with unique id {}'.format(self.id)

client_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from client_app.models import Author, Article, Comment


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def save(self, *args, **kwargs):
        django_user = User.objects.create_user(username=self.cleaned_data['username'],
                                               first_name=self.cleaned_data['first_name'],
                                               last_name=self.cleaned_data['last_name'],
                                               password=self.cleaned_data['password1'],
                                               email=self.cleaned_data['email'],
                                               is_staff=True,
                                               is_active=False if kwargs['check_mail'] else True
                                               )
        Author.objects.create(user=django_user)
        print(self.cleaned_data)
        return django_user

    def get_cleaned_data(self, *args, **kwargs):
        return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        # fields = "__all__"
        exclude = ('user',)
        # widgets = {
        #     'date_birth': forms.DateInput(format=('%m/%d/%Y'),
        #                                   attrs={'class': 'form-control',
        #                                          'placeholder': 'Select a date',
        #                                          'type': 'text'}),
        # }


class ArticleForm(forms.ModelForm):

    def save(self, *args, **kwargs):
        self.instance.author = kwargs['author']
        self.instance.save()

    class Meta:
        model = Article
        exclude = ['author', 'create_at', 'comments']


class CommentForm(forms.ModelForm):

    def save(self, commit=False, *args, **kwargs):
        print(self.instance)
        self.instance.from_user = kwargs['from_user']
        print('save comment!!!!!')
        print(kwargs['from_user'])
        self.instance.save()
        return self.instance

    class Meta:
        model = Comment
        exclude = ['from_user']

client_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .forms import AuthorForm, ArticleForm, CommentForm
from .models import Author, Article
from django.contrib.auth.models import User
from lesson_3.models import Book


@login_required(redirect_field_name=settings.LOGIN_URL)
def cabinet(request):
    ctx = {}
    ctx['cabinet_tab'] = 'main'
    if request.method == 'GET':
        try:
            author = Author.objects.get(user=request.user.id)
            ctx['form'] = AuthorForm(instance=author)
        except Exception as e:
            ctx['form'] = AuthorForm
    elif request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = Author.objects.get(user=request.user.id)
            author.date_birth = form.cleaned_data['date_birth']
            author.bio = form.cleaned_data['bio']
            author.type_view = form.cleaned_data['type_view']
            author.pseudoname = form.cleaned_data['pseudoname']
            author.save()
            ctx['save'] = True
            ctx['form'] = AuthorForm(instance=author)
        else:
            ctx['form'] = AuthorForm(request.POST)
    return render(request, 'client_app/cabinet.html', ctx)


@login_required(redirect_field_name=settings.LOGIN_URL)
def write_post(request):
    ctx = {}
    ctx['article_form'] = ArticleForm
    ctx['cabinet_tab'] = 'write_post'
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            author = Author.objects.get(user=request.user.id)
            form.save(author=author)
        else:
            ctx['article_form'] = form
    return render(request, 'client_app/write_post.html', ctx)


@login_required(redirect_field_name=settings.LOGIN_URL)
def my_articles(request):
    ctx = {}
    all_articles = Article.objects.filter(author=Author.objects.get(user=request.user.id))
    ctx['cabinet_tab'] = 'my_articles'
    ctx['all_articles'] = all_articles
    print(all_articles, len(all_articles))
    return render(request, 'client_app/my_articles.html', ctx)


def article_item(request, pk):
    ctx = {}
    article = Article.objects.get(pk=pk)
    ctx['article'] = article
    ctx['comment_form'] = CommentForm()
    return render(request, 'client_app/show_article.html', ctx)


from django.contrib import messages


def add_comment(request, article_id):
    ctx = {}
    article = Article.objects.get(pk=article_id)
    ctx['article'] = article
    print(request.GET)
    if not request.user.is_authenticated:
        ctx['messages'] = "Login please!"
        # ctx['article_id'] = article_id
        return render(request, 'client_app/show_article.html', ctx)
    if request.method == 'POST':
        print('asdasdassdas dd ad ada da dasd as')
        form = CommentForm(request.POST)
        if form.is_valid():
            article = Article.objects.get(pk=article_id)
            print('add_comment')
            print(request.user)
            print('add_comment')
            new_comment = form.save(from_user=request.user, commit=False)
            article.comments.add(new_comment)
            article.save()
            return redirect('client_app:article-item', pk=article_id)
    return redirect(request.get_absolute_url)


def filter_by_status(request, status):
    ctx = {}
    ctx['all_articles'] = None
    return render(request, 'client_app/my_articles.html', ctx)


def change_color(request):
    if request.method == 'POST':
        request.session['color'] = request.POST.get('color')  # #DF1565
    return redirect('client_app:cabinet')


def all_articles(request):
    ctx = {

    }
    all_articles = Article.objects.filter(status='publish')
    ctx['list_of_article'] = all_articles
    return render(request, 'client_app/all_articles.html', ctx)


def wish_list(request, pk):
    ctx = {}
    article_ids = request.session.get('read_article', [])
    print(article_ids)
    if pk:
        print(pk, '----------------')
        if pk in article_ids:
            article_ids.remove(pk)
            request.session['read_article'] = article_ids
    ctx['all_articles'] = [Book.objects.get(pk=elem) for elem in article_ids]
    print(article_ids)
    return render(request, 'client_app/wish_list.html', ctx)


def set_to_session(request):
    saved_list = request.session.get('read_article', [])
    saved_list.append(int(request.GET.get('article_id')))
    request.session['read_article'] = saved_list
    # request.session.clear()
    return redirect('lesson_3:home')


from django.template.loader import render_to_string


def delete_article(request, pk):
    if request.is_ajax():
        Article.objects.get(pk=int(pk)).delete()
        all_articles = Article.objects.filter(author=Author.objects.get(user=request.user.id))
        response_html = render_to_string('client_app/ajax/reload_block_articles.html', {
            'all_articles': all_articles
        })
        return JsonResponse({
            'deleted': True,
            'response_html': response_html,
            'count_articles': len(all_articles)
        })


def show_article(request, pk):
    content = Article.objects.get(id=int(pk)).content
    return JsonResponse({
        'content': content
    })


def show_article_client(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'client_app/show_article_client.html', {
        'article': article
    })

cbs/templates/client_app/all_articles.html
{% extends 'index.html' %}

{% block content %}

<h1>All article hello world )</h1>

{% for article in list_of_article %}
<div>
    #{{forloop.counter}}
    <a href="{% url 'client_app:show-article-client' pk=article.id %}">{{article.title}}</a>
    <p>{{article.author}}</p>
</div>

{% endfor %}

{% endblock %}

cbs/templates/client_app/cabinet.html
{% extends 'index.html' %}
{% block content %}
<h1>Hello {{ request.user.first_name }} {{ request.user.last_name }} !</h1>

<div class="cabinet-content row">
    <div class="left-col col-md-3 ">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link {% if cabinet_tab == 'main' %} active {% endif %}"
               href="{% url 'client_app:cabinet' %}">Мой
                профиль</a>
            <a class="nav-link {% if cabinet_tab == 'write_post' %} active {% endif %}"
               href="{% url 'client_app:write_post' %}">Написать статью</a>
            <a class="nav-link {% if cabinet_tab == 'my_articles' %} active {% endif %}"
               href="{% url 'client_app:my_articles' %}">Мои статьи</a>
            <a class="nav-link">Подписчики</a>
            <form action="{% url 'client_app:change_color' %}" method="post">
                {% csrf_token %}
                <input name="color" type="color">
                <!--<input type="range" min="0" max="500" step="50">-->
                <!--<input type="file">-->
                <button>Сменить цвет</button>
            </form>
        </div>
    </div>
    <div class="right-col col-md-9">
        {% if save %}
        <p class="alert alert-success">Успешно сохранили данные!</p>
        {% endif %}
        <div class="content-wrap">
            {% block right_col %}
            <form action="{% url 'client_app:cabinet' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.label }}
                    {{ field }}
                    {% if field.errors %}
                    {{ field.errors }}
                    {% endif %}
                </div>
                {% endfor %}
                <button>Save!</button>
            </form>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

cbs/templates/client_app/login_form.html
{% extends 'index.html' %}

{% block content %}
<h1>Login!</h1>

<a href="{% url 'client_app:register' %}">Нет аккаунта?</a>
<form action="." method="post">
    {% csrf_token %}
    <!--<div>-->
    <!--<label for="">Login</label>-->
    <!--<input type="text" name="username">-->
    <!--</div>-->
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="text" class="form-control"
               id="exampleInputEmail1" aria-describedby="emailHelp"
               name="username1">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
    </div>
    <!--<div>-->
    <!--<label for="">Password</label>-->
    <!--<input type="password" name="password">-->
    <!--</div>-->
    <button type="submit" class="btn btn-primary">Submit</button>
    {% if error %}
    <p class="alert alert-danger">{{error}}</p>
    {% endif %}
</form>


<!--<form>-->
    <!--<div class="form-group">-->
    <!--<label for="exampleInputEmail1">Email address</label>-->
    <!--<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
    <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
    <!--</div>-->
    <!--<div class="form-group">-->
        <!--<label for="exampleInputPassword1">Password</label>-->
        <!--<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">-->
    <!--</div>-->
    <!--<div class="form-check">-->
        <!--<input type="checkbox" class="form-check-input" id="exampleCheck1">-->
        <!--<label class="form-check-label" for="exampleCheck1">Check me out</label>-->
    <!--</div>-->
    <!--<button type="submit" class="btn btn-primary">Submit</button>-->
<!--</form>-->
{% endblock %}

cbs/templates/client_app/my_articles.html
{% extends 'client_app/cabinet.html' %}
{% load static %}
{% block right_col %}
    <style>
        .article-row {
            display: flex;
            align-items: center;
            border-bottom: 1px solid black;
        }

        .col {
            width: 20%;
            padding: 12px;
        }

        .article-row:nth-child(odd) {
            background: gainsboro;
        }

        .show-btn {
            background: black;
            color: white;
            padding: 10px;
            margin-left: 15px;
        }

        .popup-wrapper {
            max-height: 50vh;
            min-width: 50vw;
            padding: 20px;
            border: 1px solid black;
            box-shadow: 0px 0px 10px black;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: white;
            display: none;
            /*overflow-y: auto;*/
        }


        .close {
            position: absolute;
            right: -15px;
            top: -15px;
        }


    </style>
    <h1>My articles <span class="js-count">{{ all_articles|length }}</span>!</h1>

    <div class="article-wrapper">
        <div class="article-row">
            <div class="col-md-1">№</div>
            <div class="col-md-4">Title</div>
            <div class="col-md-4">Publish?</div>
            <div class="col-md-3">Actions</div>
        </div>
        <div class="js-article-reload">
            {% include 'client_app/ajax/reload_block_articles.html' %}
        </div>
    </div>

{% endblock %}


{% block js %}
    <script src="{% static 'js/personal_cabinet.js' %}"></script>
{% endblock %}

cbs/templates/client_app/register_form.html
{% extends 'index.html' %}

{% block content %}
    <a href="{% url 'client_app:login' %}">Есть аккаунт?</a>
    <form method="post" action="{% url 'client_app:register' %}">
        {% csrf_token %}
        {% for field in form %}
{#            <label for="check_{{ forloop.counter }}">{{ forloop.counter }}</label>#}
{#            <input type="checkbox" name="name_{{ forloop.counter }}"#}
{#                   id="check_{{ forloop.counter }}">#}
            <p>
                <label for="">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </p>
        {% endfor %}
        <label for="">Потверждать почту</label>
        <input type="checkbox" name="check_mail">
        <input type="submit" class="btn btn-success" value="Sign up">
        <input class="btn btn-danger" type="reset" value="reset">
        <!--<button>Sign up</button>-->
    </form>

{% endblock %}

cbs/templates/client_app/show_article.html
{% extends 'index.html' %}

{% block css %}
<style>
    .align-center {
        text-align: center;
    }

    textarea {
        resize: none;
        height: 150px;
    }
</style>


{% endblock %}
{% block content %}
<h1>Заголовок - {{article.title}}</h1>
<div>Контент - {{article.content|safe}}</div>
<hr>

<div class="author-wrap">
    <p>Создана - {{article.create_at}}</p>
    <p>Автор - @{{article.author.user}}</p>
</div>

<h3 class="align-center">Комментарии ({{article.comments.all|length}})</h3>

{% for comment in article.comments.all %}
<div class="media">
    <a class="pull-left" href="#">
        <p style="margin-right: 15px;">#{{forloop.counter}}</p>
    </a>
    <div class="media-body">
        <h6 class="media-heading">@{{comment.from_user}}</h6>
        {{comment.msg}}
    </div>
</div>
<hr>
{% empty %}

<h2>Коментарием пока нет... Вы можете быть первыми</h2>

{%  endfor %}
{% if messages %}
{{messages}}

{% endif %}

{# {% if request.user.is_authenticated %} #}
<form action="{% url 'client_app:add_comment' article.id %}" method="POST">
    {% csrf_token %}
    {% for field in comment_form %}
    <div>
        {{field.label_tag}}
    </div>
    {{field}}
    {% endfor %}
    <div>
        <button class="btn btn-success">Отправить</button>
    </div>
</form>

{# {% else %}#}

{#<p class="alert alert-info">Авторизируйтесь пожалуйста. #}
    {#<a href="{% url 'client_app:login' %}" class="btn btn-success">Вход</a></p>#}
{#{% endif %}#}


{% endblock %}

cbs/templates/client_app/show_article_client.html
{% extends 'index.html' %}

{% block content  %}

<h1>{{article.title}}</h1>
<p>{{article.create_at}}</p>
<p>Автор - {{article.author}}</p>

<div>
    {{article.content|safe}}
</div>

{% endblock %}

cbs/templates/client_app/wish_list.html
{% extends 'index.html' %}


{% block content %}
<div class="book-wrapper row">

    {% for article in all_articles %}
    {% include 'includes/article_item.html' with object=article del=True %}

    {% empty %}
    <p class="alert alert-warning">
        Ваш список пуст!
        <a href="{% url 'lesson_3:home' %}">Подберите себе книгу!</a>
    </p>
    {% endfor %}


</div>
{% endblock %}

cbs/templates/client_app/write_post.html
{% extends 'client_app/cabinet.html' %}

{% block right_col %}
<form action="{% url 'client_app:write_post' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ article_form.media }}
    {% for field in article_form %}
    <div>
        <label for="">{{field.label}}</label>
        {{field}}
        {% if field.errors %}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button>Save</button>
</form>

{% endblock %}