cbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('admin/', admin.site.urls),
                  path('', include('lesson_3.urls', namespace='lesson_3')),
                  path('auth-urls/', include('client_app.urls', namespace='client_app')),
                  path('vue-example/', include('vue_example.urls', namespace='vue')),
                  re_path(r'^api-auth/', include('rest_framework.urls'))
              ] + static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_app/urls.py
from django.urls import path, include, re_path
from . import views, auth_views

app_name = 'client_app'

urlpatterns = [
    path('cabinet', views.cabinet, name='cabinet'),
    path('all-articles', views.all_articles, name='all-articles'),
    path('change_color', views.change_color, name='change_color'),
    path('set-to-wish-list', views.set_to_session, name='set-to-wish-list'),
    path('write_post', views.write_post, name='write_post'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('wish-list/<int:pk>/', views.wish_list, name='wish-list'),
    path('article-item/<int:pk>',
         views.article_item,
         name='article-item'),
    path('add-commen/<int:article_id>', views.add_comment, name='add_comment'),
    path('filter_by_status/<str:status>',
         views.filter_by_status,
         name='filter_by_status'),
    path('delete_article/<int:pk>', views.delete_article, name='delete_article'),
    path('show_article/<int:pk>', views.show_article, name='show_article'),
    path('show-article-client/<int:pk>', views.show_article_client, name='show-article-client'),
]

auth_urls = [
    path('', auth_views.login_, name='login'),
    path('register', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

lesson_3/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'lesson_3'

urlpatterns = [
    path('', views.index, name='home'),
    path('all-authors', views.all_authors, name='authors'),
    path('book-info/<int:pk>', views.book_info, name='book-info'),
    path('all_book_for_authors/<int:id_author>',
         views.all_book_for_authors,
         name='all_book_for_authors'),
    path('calc', views.calc, name='calc'),
]

vue_example/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'vue'
urlpatterns = [
    path('', views.main_vue, name='main'),
    path('api/', include('vue_example.api_urls')),

]

cbs/templates/includes/article_item.html
<div class=" col-md-4 card book-item {% if object.is_sale %} sale {% endif %}" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">{{object.title}}</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@{{object.author.get_full_name}}</li>
    </ul>
    <div class="card-body">
        <a class="btn btn-link" href="{% url 'lesson_3:book-info' pk=object.id %}" class="card-link">Читать</a>
    </div>
    {% if del == True %}
    <a class="btn btn-danger" href="{% url 'client_app:wish-list' pk=object.id %}">Удалить</a>
    {% else %}
    <form action="{% url 'client_app:set-to-wish-list' %}" >
        <input type="hidden" name="article_id" value = {{object.id}}>
        <button>Отложить на чтение</button>
    </form>
    {% endif %}
</div>

cbs/templates/includes/footer.html
<footer>
    footer!
</footer>

cbs/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">CBS DJANGO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url  'lesson_3:home' %}">Все книги<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url  'lesson_3:authors' %}">Все авторы</a>
            </li>


            <li class="nav-item active">
                <a class="nav-link" href="{% url 'client_app:all-articles' %}">Все статьи от пользователей<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    примеры
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'lesson_3:calc' %}">Calculator</a>
                    <a class="dropdown-item" href="{% url 'vue:main' %}">Example vue</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <a class="btn btn-info" href="{% url 'client_app:cabinet' %}">Мой кабинет</a>
            {% if request.user.is_authenticated %}
                <a class="btn btn-success" href="{% url 'client_app:logout' %}">Выход({{ request.user.username }})</a>
            {% else %}
                <a href="{% url 'client_app:login' %}" class="btn btn-success">Вход</a>
                <a href="{% url 'client_app:register' %}" class="btn btn-primary">Регистрация</a>
            {% endif %}

        </ul>
        <a href="{% url 'client_app:wish-list' pk=0 %}"
           class="btn btn-warning">
            Не забыть почитать ({{ request.session.read_article|length }})
        </a>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>